### ISSUE TITLE
DeadObjectException

### ISSUE THREAD

**Issue by DaRkRaGe** [playgameservices/android-basic-samples#238]
Fatal Exception: java.lang.RuntimeException: android.os.DeadObjectException
       at android.app.ApplicationPackageManager.getPackageInstaller(ApplicationPackageManager.java:1650)
       at com.google.android.gms.common.zze.zzs(Unknown Source)
       at com.google.android.gms.common.zzc.zzs(Unknown Source)
       at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source)
       at com.google.android.gms.internal.zzaal.zzvK(Unknown Source)
       at com.google.android.gms.internal.zzaal.zzc(Unknown Source)
       at com.google.android.gms.internal.zzaai.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.internal.zzaan.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.internal.zzzy.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzl$1.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:504)
       at android.content.pm.IPackageManager$Stub$Proxy.getPackageInstaller(IPackageManager.java:4405)
       at android.app.ApplicationPackageManager.getPackageInstaller(ApplicationPackageManager.java:1647)
       at com.google.android.gms.common.zze.zzs(Unknown Source)
       at com.google.android.gms.common.zzc.zzs(Unknown Source)
       at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source)
       at com.google.android.gms.internal.zzaal.zzvK(Unknown Source)
       at com.google.android.gms.internal.zzaal.zzc(Unknown Source)
       at com.google.android.gms.internal.zzaai.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.internal.zzaan.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.internal.zzzy.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzl$1.onConnectionSuspended(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5696)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by mdvx** [comment]
currently my most frequent crash

**Comment by hetalraichura** [comment]
I am facing the same crash.

**Comment by fdotergun** [comment]
Getting this crash i couldn't find a solution.

**Comment by mwgray** [comment]
Hi all,

Are you still seeing this behavior with the latest code?  Which project is it?  Can you post any repro steps?

**Comment by mdvx** [comment]
No, Have not seen this for a while

**Comment by mwgray** [comment]
Okay, going to close for now.  If it comes up again, feel free to re-open with steps to reproduce.

**Comment by j05u3** [comment]
Hi, I am using play services 10.0.0 and receiving the same trace:
http://crashes.to/s/a6e6f08d5eb
