### ISSUE TITLE
There is no linked app associated with this client ID

### ISSUE THREAD

**Issue by gembutterfly** [playgameservices/android-basic-samples#249]
I know there are similar questions here already, but none of them contained a proper solution to this issue.

I have a libgdx project with enabled Google Play Games Services and matching SHA1 fingerprints. This problem happens after submitting the first score to a leaderboard, after this, the leaderboard can not be displayed anymore and the request returns this error:

```
14104-14148/com.google.android.gms E/Volley: [568] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/applications/played
06-14 12:12:50.358 14104-17900/com.google.android.gms W/GameAgent: Volley error when reporting played
                                                                   com.android.volley.AuthFailureError
                                                                       at com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms:32)
                                                                       at lbf.performRequest(:com.google.android.gms:3)
                                                                       at com.android.volley.NetworkDispatcher.run(:com.google.android.gms:11)
06-14 12:12:50.360 2953-12624/system_process E/AlarmManagerService: Unable to set alarm to 1497513600.000000000: Invalid argument
06-14 12:12:50.669 14104-14147/com.google.android.gms E/Volley: [567] BasicNetwork.performRequest: Unexpected response code 401 for https://www.googleapis.com/games/v1/leaderboards/scores?language=de_DE
06-14 12:12:50.675 2953-3084/system_process E/AlarmManagerService: Unable to set alarm to 1497513600.000000000: Invalid argument
06-14 12:12:50.812 14104-17901/com.google.android.gms E/MultiDataOperation: There is no linked app associated with this client ID.
                                                                            com.google.android.gms.games.server.error.GamesException
                                                                                at com.google.android.gms.games.server.GamesServer.getResponseBlocking(GamesServer.java:174)
                                                                                at com.google.android.gms.games.broker.LeaderboardAgent.submitMultipleBlocking(LeaderboardAgent.java:969)
                                                                                at com.google.android.gms.games.broker.LeaderboardAgent.submitBatchedBlocking(LeaderboardAgent.java:891)
                                                                                at com.google.android.gms.games.broker.LeaderboardAgent.flushPendingScores(LeaderboardAgent.java:858)
                                                                                at com.google.android.gms.games.broker.LeaderboardAgent.getRootPage(LeaderboardAgent.java:1068)
                                                                                at com.google.android.gms.games.broker.DataBroker.getTopScoresPage(DataBroker.java:915)
                                                                                at com.google.android.gms.games.service.operations.leaderboards.LoadScoresOperation.fetchData$b7c4c52(LoadScoresOperation.java:50)
                                                                                at com.google.android.gms.games.service.operations.AbstractMultiDataHolderOperation.execute(AbstractMultiDataHolderOperation.java:53)
                                                                                at com.google.android.gms.games.service.operations.GamesOperationAdapter.execute(GamesOperationAdapter.java:23)
                                                                                at com.google.android.gms.chimera.BaseAsyncOperationService$OperationTask.run(BaseAsyncOperationService.java:177)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)
06-14 12:12:50.825 2953-7238/system_process I/WindowManager: setFocusedApp token: Token{6e9cc60 ActivityRecord{6b16863 u0 de.limbusdev.snakebites.tv.lite/.AndroidLauncher t884}} requestedOrientation: 0
06-14 12:12:50.836 17350-17350/de.limbusdev.snakebites.tv.lite D/GameHelper: GameHelper: onActivityResult: req=5001, resp=RESULT_RECONNECT_REQUIRED
06-14 12:12:50.836 17350-17350/de.limbusdev.snakebites.tv.lite D/GameHelper: GameHelper: onActivityResult: request code not meant for us. Ignoring.
```

Hope someone can help. I am really desperate right now :(

Cheers, Gem

**Comment by gembutterfly** [comment]
PS: using Google Play App Signing - might that have to so something with it?

**Comment by gembutterfly** [comment]
Finally gave up.

Instead I changed the package name and released the app as a new one, used new keystores and a new play game service.

Now it works.
