### ISSUE TITLE
Unexpected response code 500 from Backend

### ISSUE THREAD

**Issue by Sca09** [playgameservices/android-basic-samples#284]
Hi,

 I just found out that my user lost all the data related to my game and all the pending matches. Debugging it I can see an 500 error from backend when trying to log in:

```
09-29 14:04:18.598 2477-4499/? E/Volley: [207] BasicNetwork.performRequest: Unexpected response code 500 for https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=es-ES&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106&requestingPackageName=com.bsidebprojects.wayofthedragon
09-29 14:04:18.602 2477-32744/? W/MultiplayerAgent: {"code":500,"errors":[{"reason":"backendError","domain":"global","message":"Backend Error"}]}
09-29 14:04:18.704 2217-3417/? I/GCM.HTTP: Last HTTP status code for blocked entry: 500
09-29 14:04:18.704 2217-3417/? W/GCM.HTTP: HTTP request blocked due to automatic backoff: https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=es-ES&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106&requestingPackageName=com.bsidebprojects.wayofthedragon
09-29 14:04:18.705 2477-4500/? W/GoogleURLConnFactory: Blocked by temporary_blocked2: https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=es-ES&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106&requestingPackageName=com.bsidebprojects.wayofthedragon
09-29 14:04:18.819 30044-604/? W/System.err: com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable
    <HTML>
09-29 14:04:18.820 30044-604/? W/System.err: <HEAD>
    <TITLE>Service Unavailable</TITLE>
    </HEAD>
    <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
    <H1>Service Unavailable</H1>
    <H2>Error 503</H2>
    </BODY>
    </HTML>
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.bsidebprojects.wayofthedragon.ChatUtils$4.doInBackground(ChatUtils.java:101)
        at com.bsidebprojects.wayofthedragon.ChatUtils$4.doInBackground(ChatUtils.java:94)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
09-29 14:04:18.821 30044-604/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

 The problem seems to be similar to some old, closed ones: https://github.com/playgameservices/android-basic-samples/issues/147 & https://github.com/playgameservices/android-basic-samples/issues/175

 
- Other users are able to login properly and recover all their data/matches, but those waiting for me to play are totally stuck now. 

- If I create a new match it is created properly but when the rest of players play my match is not updated so for me it's not my turn but for them it is still my turn.

- I am not aware of new matches created by others with me.

- Login in takes way longer than usual until I get the 500 error.

- Testing my account in other device I still find issues, not matches recovered neither the ones created by me since the issue started.

 
 Cheers
 David Torralbo

**Comment by jorgelamb** [comment]
+1, I have the same issue, same exact description of the problem, and same thing on the logs: "Backend error". The stack trace is for some unrelated thing, the important part are the two first lines:

`9-29 14:04:18.598 2477-4499/? E/Volley: [207] BasicNetwork.performRequest: Unexpected response code 500 for https://www.googleapis.com/games/v1whitelisted/multiplayerentities/sync?language=es-ES&matchType=real_time&matchType=turn_based&maxCompletedMatchesPerApp=10&platformType=ANDROID&requestingApplicationId=691821631106&requestingPackageName=com.bsidebprojects.wayofthedragon
09-29 14:04:18.602 2477-32744/? W/MultiplayerAgent: {"code":500,"errors":[{"reason":"backendError","domain":"global","message":"Backend Error"}]}
`
