### ISSUE TITLE
Internal error when opening Saved Games UI

### ISSUE THREAD

**Issue by obigu** [playgameservices/android-basic-samples#286]
We have recently started receiving reports from users on of a crash when opening the default GPGS Saved Games UI. The app has been live for a long time now without issues and the logic it uses has not 
changed and it's been taken directly from the official docs (https://developers.google.com/games/services/android/savedgames#displaying_saved_games).

We've reproduced it and this is the crash report:
```
11-11 00:40:08.126 9307-9307/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.play.games.ui, PID: 9307
    java.lang.NullPointerException: null reference
        at goo.a(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):1)
        at kkb.a(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):9)
        at kkl.a(Unknown Source:4)
        at kkv.b(Unknown Source:21)
        at kkv.a(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):1)
        at kkb.a(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):12)
        at kkk.a(Unknown Source:4)
        at bsc.b(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):38)
        at bsc.e(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):5)
        at bsc.f_(Unknown Source:5)
        at bth.handleMessage(:com.google.android.play.games@74660040@5.13.7466 (218554949.218554949-000400):20)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The issue seems to be related to the latest Google Play Services version and not to a specific change on our app as we can also reproduce it on previous production APKs that worked without any issue.

**UPDATE 2: The issue reproduces on Google Play Games version 5.13.7466 tested on an Android 9, Android 8.1 and an Android 6.0.1 device. It works correctly on Google Play Games 5.10 which confirms it's a bug on the latest version of Google Play Games.**

**Comment by tm0ngy** [comment]
I'm having the exact same problem in my game. Did you manage to find any soultion to this?

**Comment by obigu** [comment]
@tm0ngy No, it's a bug on GPGS latest version, hopefully Google team will see this and work on a fix for the next version. What I've noticed is that an old project based on the old BaseGameUtils class doesn't fail and that's probably why it doesn't affect all games but just the ones implemented in the new recommended manner.

**Comment by tm0ngy** [comment]
@obigu Yeah I hope they fix it soon. I've noticed that sometimes if I start the "Play Games" app on the phone before I launch my app, the saved games UI shows up normally. But then, if the saved game is modified by playing the game, the saved game UI crashes with the same error you posted above again.

**Comment by obigu** [comment]
In my case my app doesn't save automatically but I also see a similar behaviour. When the app has just been installed, the first time the Saved Games UI is opened it works fine. From then on, unless you do a Clear Data on the Google Play Games app, it fails on subsequent attempts to open it.

**Comment by tm0ngy** [comment]
Seems the issue is finally fixed in the new version of Google Play Games (5.14.7825)

**Comment by obigu** [comment]
> Seems the issue is finally fixed in the new version of Google Play Games (5.14.7825)

Yup, closing issue
