### ISSUE TITLE
java.lang.IllegalArgumentException after update to com.google.android.gms:play-services-games:17.0.0

### ISSUE THREAD

**Issue by denri11** [playgameservices/android-basic-samples#290]
In our game implemented online multiplayer using Google Play Game services.
After updating **com.google.android.gms:play-services-games** to version **17.0.0**, the console often began to receive a new error:

#### Log
```java
java.lang.IllegalArgumentException: 
  at com.google.android.gms.common.data.DataHolder.zaa (Unknown Source:159)
  at com.google.android.gms.common.data.DataHolder.getLong (Unknown Source:166)
  at com.google.android.gms.common.data.DataBufferRef.getLong (Unknown Source:12)
  at com.google.android.gms.games.PlayerRef.zzo (Unknown Source:59)
  at com.google.android.gms.games.PlayerEntity.<init> (Unknown Source:28)
  at com.google.android.gms.games.PlayerEntity.<init> (Unknown Source:1)
  at com.google.android.gms.games.multiplayer.ParticipantEntity.<init> (Unknown Source:12)
  at com.google.android.gms.games.multiplayer.ParticipantEntity.zza (Unknown Source:7)
  at com.google.android.gms.games.multiplayer.realtime.RoomEntity.<init> (Unknown Source:1)
  at com.google.android.gms.games.multiplayer.realtime.zzf.freeze (Unknown Source:36)
  at com.google.android.gms.games.internal.zze.zzay (Unknown Source:746)
  at com.google.android.gms.games.internal.zze.zzaz (Unknown Source:796)
  at com.google.android.gms.games.internal.zzx.notifyListener (Unknown Source:2)
  at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal (Unknown Source:17)
  at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage (Unknown Source:5)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6626)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)
```
We had to go back to version 16.0.0

**Comment by stepanov-standy** [comment]
I do confirm an issue in 17.0.0. Please fix ASAP:

Non-fatal Exception: java.lang.IllegalArgumentException: No such column: total_unlocked_achievements
       at com.google.android.gms.common.data.DataHolder.zaa(DataHolder.java:159)
       at com.google.android.gms.common.data.DataHolder.getLong(DataHolder.java:166)
       at com.google.android.gms.common.data.DataBufferRef.getLong(DataBufferRef.java:12)
       at com.google.android.gms.games.PlayerRef.zzo(PlayerRef.java:59)
       at com.google.android.gms.games.PlayerEntity.(Unknown Source:28)
       at com.google.android.gms.games.PlayerEntity.(Unknown Source:1)
       at com.google.android.gms.games.multiplayer.ParticipantEntity.(Unknown Source:12)
       at com.google.android.gms.games.multiplayer.ParticipantEntity.zza(ParticipantEntity.java:7)
       at com.google.android.gms.games.multiplayer.realtime.RoomEntity.(Unknown Source:1)
       at com.google.android.gms.games.multiplayer.realtime.zzf.freeze(zzf.java:36)
       at com.google.android.gms.games.internal.zze.zzay(zze.java:746)
       at com.google.android.gms.games.internal.zze.zzaz(zze.java:796)
       at com.google.android.gms.games.internal.zzx.notifyListener(zzx.java:2)
       at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(ListenerHolder.java:17)
       at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(ListenerHolder.java:5)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by denri11** [comment]
After updating **com.google.android.gms:play-services-games** to version **18.0.0** the error continues to come to the Google Play console. We use Achievements, Leaderboards, Saved Games and Real-time Multiplayer. Any ideas on that?

**Comment by ssicosm** [comment]
I am experiencing the same error.

**Comment by nfunky** [comment]
same error for me, worked again after reverting to version 16.0.0
