### ISSUE TITLE
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.games.snapshot.SnapshotMetadataEntity

### ISSUE THREAD

**Issue by jjmartinezdarc** [playgameservices/android-basic-samples#307]
I'm facing error when trying to load snapshot from saved games. It is working in debug build, but when I tried to download it from internal testing this error always occurs

Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.gms.games.snapshot.SnapshotMetadataEntity
        at android.os.Parcel.readParcelableCreator(Parcel.java:2831)
        at android.os.Parcel.readParcelable(Parcel.java:2757)
        at android.os.Parcel.readValue(Parcel.java:2660)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3029)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.containsKey(BaseBundle.java:504)
        at android.content.Intent.hasExtra(Intent.java:7257)
        at com.myapps.app.MainActivity.onActivityResult(Unknown Source:18)
        at android.app.Activity.dispatchActivityResult(Activity.java:7454)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)

**Comment by jjmartinezdarc** [comment]
I already solved it by adding pro guard configuration described [here](https://developer.android.com/topic/google-play-instant/getting-started/support-play-games-services)

**Comment by jjmartinezdarc** [comment]
I already solved it. Since my release build is using pro guard I needed to add some configuration described [here](https://developer.android.com/topic/google-play-instant/getting-started/support-play-games-services)
