### ISSUE TITLE
Avatar image must be squared. ClientRequestInboxListActivit has crashed.

### ISSUE THREAD

**Issue by dalinaum** [playgameservices/android-basic-samples#69]
I had implemented sending gifts and requests and invoking inbox. I has tested with some friends. Some friends could send hearts to me. So I has uloaded my apk to Play. When one friend has send a request to me, my inbox has broken.

````
E/AndroidRuntime(29235): FATAL EXCEPTION: main
E/AndroidRuntime(29235): Process: com.google.android.gms.ui, PID: 29235
E/AndroidRuntime(29235): java.lang.IllegalArgumentException: Avatar image must be squared
E/AndroidRuntime(29235): 	at bio.a(SourceFile:25)
E/AndroidRuntime(29235): 	at big.a(SourceFile:284)
E/AndroidRuntime(29235): 	at bib.run(SourceFile:614)
E/AndroidRuntime(29235): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(29235): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(29235): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(29235): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime(29235): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29235): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(29235): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime(29235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime(29235): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  768):   Force finishing activity com.google.android.gms/.games.ui.client.requests.ClientRequestInboxListActivity
W/ActivityManager(  768):   Force finishing activity com.lazybeeinc.ZombieAway/.ZombieAway
````

**Comment by claywilkinson** [comment]
Closing old issues - please reopen if you have more questions.
