### ISSUE TITLE
Game Save API - Snapshots - Unresolvable conflict

### ISSUE THREAD

**Issue by MonsterOfCookie** [playgameservices/android-basic-samples#90]
I have been experimenting with code in Collect All the Stars 2 for the Save Game API. However I am able to get my device into a state where when I open the snapshot, the result has a status code of 4004, and no matter how often I let the conflict resolution code execute (I upped it from the 3 in the example to 10) the resolveConflict is always has a returning code of 4004. Thus I can never resolve this conflict.

The following is the stack trace from the open call.

```
07-16 20:43:04.466  16624-16794/? I/qtaguid﹕ Failed write_ctrl(u 48) res=-1 errno=22
07-16 20:43:04.466  16624-16794/? I/qtaguid﹕ Untagging socket 48 failed errno=-22
07-16 20:43:04.466  16624-16794/? W/NetworkManagementSocketTagger﹕ untagSocket(48) failed with errno -22
07-16 20:43:04.496     846-1637/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:04.977  16624-16795/? I/qtaguid﹕ Failed write_ctrl(u 48) res=-1 errno=22
07-16 20:43:04.977  16624-16795/? I/qtaguid﹕ Untagging socket 48 failed errno=-22
07-16 20:43:04.977  16624-16795/? W/NetworkManagementSocketTagger﹕ untagSocket(48) failed with errno -22
07-16 20:43:04.987  16624-16795/? E/Volley﹕ [1598] tm.a: Unexpected response code 404 for https://www.googleapis.com/drive/v2internal/files/1A5eHCQg6vUUSG4HSfGpIY0ddWM4jB2KK9LcR8_S5MebaAOWwETdywBIhlEEPvhdNuCHV6zY?prettyPrint=false&fields=parents(isRoot,id),md5Checksum,etag,embedLink,userPermission(role),localId(value,space,version),downloadUrl,lastViewedByMeDate,webContentLink,id,fileSize,alternateLink,title,webViewLink,sharedWithMeDate,description,createdDate,mimeType,shared,fileExtension,appDataContents,modifiedByMeDate,labels(restricted,viewed,starred,trashed),quotaBytesUsed,properties(value,visibility,key,appId),ownerNames,modifiedDate,editable,authorizedAppIds,copyable,indexableText(text),thumbnail(image,mimeType),thumbnailLink,explicitlyTrashed,headRevisionId,creatorAppId&allProperties=true&fileScopeAppIds=634219168540&updateViewedDate=false
07-16 20:43:04.987  16624-22256/? W/SingleItemSynchronizer﹕ Remote request failed
    java.io.IOException: tg
            at dfy.c(SourceFile:269)
            at dfy.a(SourceFile:243)
            at clr.a(SourceFile:78)
            at clr.a(SourceFile:109)
            at cex.a(SourceFile:917)
            at cge.a(SourceFile:40)
            at cfq.b(SourceFile:33)
            at cfp.a(SourceFile:38)
            at cfo.a(SourceFile:22)
            at caa.onHandleIntent(SourceFile:60)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: tg
            at tm.a(SourceFile:146)
            at sq.run(SourceFile:110)
07-16 20:43:05.207    846-20075/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:05.277    931-22254/? W/SnapshotAgent﹕ Found multiple files with title, taking the oldest one
07-16 20:43:05.417      846-857/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:05.887  16624-16797/? I/qtaguid﹕ Failed write_ctrl(u 48) res=-1 errno=22
07-16 20:43:05.887  16624-16797/? I/qtaguid﹕ Untagging socket 48 failed errno=-22
07-16 20:43:05.887  16624-16797/? W/NetworkManagementSocketTagger﹕ untagSocket(48) failed with errno -22
```

Then from the conflict resolution code
```
07-16 20:43:06.458    931-22299/? W/SnapshotAgent﹕ Found multiple files with title, taking the oldest one
07-16 20:43:06.568    846-20075/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:06.578  16624-22284/? W/RateLimitedExecutor﹕ Dropping request, as an updater is already scheduled.
07-16 20:43:06.628      846-983/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:07.019  16624-16796/? I/qtaguid﹕ Failed write_ctrl(u 48) res=-1 errno=22
07-16 20:43:07.019  16624-16796/? I/qtaguid﹕ Untagging socket 48 failed errno=-22
07-16 20:43:07.019  16624-16796/? W/NetworkManagementSocketTagger﹕ untagSocket(48) failed with errno -22
07-16 20:43:07.219  16624-16794/? I/qtaguid﹕ Failed write_ctrl(u 69) res=-1 errno=22
07-16 20:43:07.219  16624-16794/? I/qtaguid﹕ Untagging socket 69 failed errno=-22
07-16 20:43:07.229  16624-16794/? W/NetworkManagementSocketTagger﹕ untagSocket(69) failed with errno -22
07-16 20:43:07.299      846-983/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:07.379    931-22318/? W/SnapshotAgent﹕ Found multiple files with title, taking the oldest one
07-16 20:43:07.439     846-1013/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:07.469  16624-16628/? D/dalvikvm﹕ GC_CONCURRENT freed 1347K, 10% free 12819K/14236K, paused 2ms+5ms, total 70ms
07-16 20:43:07.739  16624-16795/? I/qtaguid﹕ Failed write_ctrl(u 69) res=-1 errno=22
07-16 20:43:07.739  16624-16795/? I/qtaguid﹕ Untagging socket 69 failed errno=-22
07-16 20:43:07.739  16624-16795/? W/NetworkManagementSocketTagger﹕ untagSocket(69) failed with errno -22
07-16 20:43:07.800  16624-22323/? W/DatabaseModelLoader﹕ Fetching application/vnd.google-play-games.snapshot as MIME type application/vnd.google-play-games.snapshot-initial: 1A5eHCQg6vUUSG4HSfGpIY0ddWM4jB2KK9LcR8_S5MebaAOWwETdywBIhlEEPvhdNuCHV6zY
07-16 20:43:07.900      846-983/? W/GLSUser﹕ GoogleAccountDataService.getToken()
07-16 20:43:08.240  16624-16797/? I/qtaguid﹕ Failed write_ctrl(u 69) res=-1 errno=22
07-16 20:43:08.240  16624-16797/? I/qtaguid﹕ Untagging socket 69 failed errno=-22
07-16 20:43:08.250  16624-16797/? W/NetworkManagementSocketTagger﹕ untagSocket(69) failed with errno -22
```

**Comment by claywilkinson** [comment]
Closing this issue - I believe it is resolved and it has been a long time with no activity.  Please open another issue if you still have questions.
